[project]
name = "notas-colab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ćhamu", email = "ajc@dnic.gob.ar" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.2",
]

[project.scripts]
notas-colab = "notas_colab:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
