# Generated by Django 6.1.2 on 2026-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
